# Generated by Django 4.1.2 on 2022-10-05 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="club",
            name="description",
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
    ]
