# Generated by Django 4.1.2 on 2022-10-05 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_initial"),
        ("clubs", "0003_alter_amenity_options_club_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="categories.category",
            ),
        ),
    ]
