# Generated by Django 4.1.2 on 2022-10-06 00:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("clubs", "0004_club_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="club",
            name="amenities",
            field=models.ManyToManyField(related_name="clubs", to="clubs.amenity"),
        ),
        migrations.AlterField(
            model_name="club",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clubs",
                to="categories.category",
            ),
        ),
        migrations.AlterField(
            model_name="club",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clubs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
