# Generated by Django 4.1.2 on 2022-10-19 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0005_alter_club_amenities_alter_club_category_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="club",
            old_name="clubs",
            new_name="locker_room",
        ),
    ]
