# Generated by Django 4.1.2 on 2022-10-26 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0006_rename_clubs_club_locker_room"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="close_time",
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name="club",
            name="open_time",
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name="club",
            name="description",
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
